spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram2024_v3
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 5MB

file:
  directory: D:\2024_BACK_JI\download\greengram_tdd_ji

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10

  cache:
    disabled: true
